# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from orbbec_camera/DeviceStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class DeviceStatus(genpy.Message):
  _md5sum = "5cf8d5046efc1ba84cc148313b15c5cc"
  _type = "orbbec_camera/DeviceStatus"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

# --- Color stream ---
float64 color_frame_rate_cur
float64 color_frame_rate_avg
float64 color_frame_rate_min
float64 color_frame_rate_max

float64 color_delay_ms_cur
float64 color_delay_ms_avg
float64 color_delay_ms_min
float64 color_delay_ms_max

# --- Depth stream ---
float64 depth_frame_rate_cur
float64 depth_frame_rate_avg
float64 depth_frame_rate_min
float64 depth_frame_rate_max

float64 depth_delay_ms_cur
float64 depth_delay_ms_avg
float64 depth_delay_ms_min
float64 depth_delay_ms_max

# --- Device info ---
bool device_online
string connection_type   # e.g. "USB2.0", "USB3.0", "GigE"

# --- Calibration status ---
bool customer_calibration_ready
bool calibration_from_factory
bool calibration_from_launch_param

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','color_frame_rate_cur','color_frame_rate_avg','color_frame_rate_min','color_frame_rate_max','color_delay_ms_cur','color_delay_ms_avg','color_delay_ms_min','color_delay_ms_max','depth_frame_rate_cur','depth_frame_rate_avg','depth_frame_rate_min','depth_frame_rate_max','depth_delay_ms_cur','depth_delay_ms_avg','depth_delay_ms_min','depth_delay_ms_max','device_online','connection_type','customer_calibration_ready','calibration_from_factory','calibration_from_launch_param']
  _slot_types = ['std_msgs/Header','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','bool','string','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,color_frame_rate_cur,color_frame_rate_avg,color_frame_rate_min,color_frame_rate_max,color_delay_ms_cur,color_delay_ms_avg,color_delay_ms_min,color_delay_ms_max,depth_frame_rate_cur,depth_frame_rate_avg,depth_frame_rate_min,depth_frame_rate_max,depth_delay_ms_cur,depth_delay_ms_avg,depth_delay_ms_min,depth_delay_ms_max,device_online,connection_type,customer_calibration_ready,calibration_from_factory,calibration_from_launch_param

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DeviceStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.color_frame_rate_cur is None:
        self.color_frame_rate_cur = 0.
      if self.color_frame_rate_avg is None:
        self.color_frame_rate_avg = 0.
      if self.color_frame_rate_min is None:
        self.color_frame_rate_min = 0.
      if self.color_frame_rate_max is None:
        self.color_frame_rate_max = 0.
      if self.color_delay_ms_cur is None:
        self.color_delay_ms_cur = 0.
      if self.color_delay_ms_avg is None:
        self.color_delay_ms_avg = 0.
      if self.color_delay_ms_min is None:
        self.color_delay_ms_min = 0.
      if self.color_delay_ms_max is None:
        self.color_delay_ms_max = 0.
      if self.depth_frame_rate_cur is None:
        self.depth_frame_rate_cur = 0.
      if self.depth_frame_rate_avg is None:
        self.depth_frame_rate_avg = 0.
      if self.depth_frame_rate_min is None:
        self.depth_frame_rate_min = 0.
      if self.depth_frame_rate_max is None:
        self.depth_frame_rate_max = 0.
      if self.depth_delay_ms_cur is None:
        self.depth_delay_ms_cur = 0.
      if self.depth_delay_ms_avg is None:
        self.depth_delay_ms_avg = 0.
      if self.depth_delay_ms_min is None:
        self.depth_delay_ms_min = 0.
      if self.depth_delay_ms_max is None:
        self.depth_delay_ms_max = 0.
      if self.device_online is None:
        self.device_online = False
      if self.connection_type is None:
        self.connection_type = ''
      if self.customer_calibration_ready is None:
        self.customer_calibration_ready = False
      if self.calibration_from_factory is None:
        self.calibration_from_factory = False
      if self.calibration_from_launch_param is None:
        self.calibration_from_launch_param = False
    else:
      self.header = std_msgs.msg.Header()
      self.color_frame_rate_cur = 0.
      self.color_frame_rate_avg = 0.
      self.color_frame_rate_min = 0.
      self.color_frame_rate_max = 0.
      self.color_delay_ms_cur = 0.
      self.color_delay_ms_avg = 0.
      self.color_delay_ms_min = 0.
      self.color_delay_ms_max = 0.
      self.depth_frame_rate_cur = 0.
      self.depth_frame_rate_avg = 0.
      self.depth_frame_rate_min = 0.
      self.depth_frame_rate_max = 0.
      self.depth_delay_ms_cur = 0.
      self.depth_delay_ms_avg = 0.
      self.depth_delay_ms_min = 0.
      self.depth_delay_ms_max = 0.
      self.device_online = False
      self.connection_type = ''
      self.customer_calibration_ready = False
      self.calibration_from_factory = False
      self.calibration_from_launch_param = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_16dB().pack(_x.color_frame_rate_cur, _x.color_frame_rate_avg, _x.color_frame_rate_min, _x.color_frame_rate_max, _x.color_delay_ms_cur, _x.color_delay_ms_avg, _x.color_delay_ms_min, _x.color_delay_ms_max, _x.depth_frame_rate_cur, _x.depth_frame_rate_avg, _x.depth_frame_rate_min, _x.depth_frame_rate_max, _x.depth_delay_ms_cur, _x.depth_delay_ms_avg, _x.depth_delay_ms_min, _x.depth_delay_ms_max, _x.device_online))
      _x = self.connection_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3B().pack(_x.customer_calibration_ready, _x.calibration_from_factory, _x.calibration_from_launch_param))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 129
      (_x.color_frame_rate_cur, _x.color_frame_rate_avg, _x.color_frame_rate_min, _x.color_frame_rate_max, _x.color_delay_ms_cur, _x.color_delay_ms_avg, _x.color_delay_ms_min, _x.color_delay_ms_max, _x.depth_frame_rate_cur, _x.depth_frame_rate_avg, _x.depth_frame_rate_min, _x.depth_frame_rate_max, _x.depth_delay_ms_cur, _x.depth_delay_ms_avg, _x.depth_delay_ms_min, _x.depth_delay_ms_max, _x.device_online,) = _get_struct_16dB().unpack(str[start:end])
      self.device_online = bool(self.device_online)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.connection_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.connection_type = str[start:end]
      _x = self
      start = end
      end += 3
      (_x.customer_calibration_ready, _x.calibration_from_factory, _x.calibration_from_launch_param,) = _get_struct_3B().unpack(str[start:end])
      self.customer_calibration_ready = bool(self.customer_calibration_ready)
      self.calibration_from_factory = bool(self.calibration_from_factory)
      self.calibration_from_launch_param = bool(self.calibration_from_launch_param)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_16dB().pack(_x.color_frame_rate_cur, _x.color_frame_rate_avg, _x.color_frame_rate_min, _x.color_frame_rate_max, _x.color_delay_ms_cur, _x.color_delay_ms_avg, _x.color_delay_ms_min, _x.color_delay_ms_max, _x.depth_frame_rate_cur, _x.depth_frame_rate_avg, _x.depth_frame_rate_min, _x.depth_frame_rate_max, _x.depth_delay_ms_cur, _x.depth_delay_ms_avg, _x.depth_delay_ms_min, _x.depth_delay_ms_max, _x.device_online))
      _x = self.connection_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3B().pack(_x.customer_calibration_ready, _x.calibration_from_factory, _x.calibration_from_launch_param))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 129
      (_x.color_frame_rate_cur, _x.color_frame_rate_avg, _x.color_frame_rate_min, _x.color_frame_rate_max, _x.color_delay_ms_cur, _x.color_delay_ms_avg, _x.color_delay_ms_min, _x.color_delay_ms_max, _x.depth_frame_rate_cur, _x.depth_frame_rate_avg, _x.depth_frame_rate_min, _x.depth_frame_rate_max, _x.depth_delay_ms_cur, _x.depth_delay_ms_avg, _x.depth_delay_ms_min, _x.depth_delay_ms_max, _x.device_online,) = _get_struct_16dB().unpack(str[start:end])
      self.device_online = bool(self.device_online)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.connection_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.connection_type = str[start:end]
      _x = self
      start = end
      end += 3
      (_x.customer_calibration_ready, _x.calibration_from_factory, _x.calibration_from_launch_param,) = _get_struct_3B().unpack(str[start:end])
      self.customer_calibration_ready = bool(self.customer_calibration_ready)
      self.calibration_from_factory = bool(self.calibration_from_factory)
      self.calibration_from_launch_param = bool(self.calibration_from_launch_param)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_16dB = None
def _get_struct_16dB():
    global _struct_16dB
    if _struct_16dB is None:
        _struct_16dB = struct.Struct("<16dB")
    return _struct_16dB
_struct_3B = None
def _get_struct_3B():
    global _struct_3B
    if _struct_3B is None:
        _struct_3B = struct.Struct("<3B")
    return _struct_3B
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
